-- <리뷰페이지 조회(가게)>
SELECT
    RI.O_NUM, U.U_NNAME, RI.R_CONTENT, RI.R_SCORE, RI.R_WRIDATE, R.R_BNAME, R.R_IMG
FROM REVIEW_INFO RI
JOIN ORDER_INFO OI ON RI.O_NUM = OI.O_NUM
JOIN USER_INFO U ON OI.U_ID = U.U_ID
JOIN REST_INFO R ON OI.R_ID = R.R_ID
WHERE R.R_ID = 1
ORDER BY RI.R_WRIDATE DESC;
-- <리뷰페이지 조회(유저)>
SELECT
    RI.O_NUM, U.U_NNAME, RI.R_CONTENT, RI.R_SCORE, RI.R_WRIDATE, R.R_BNAME, R.R_IMG
FROM REVIEW_INFO RI
JOIN ORDER_INFO OI ON RI.O_NUM = OI.O_NUM
JOIN USER_INFO U ON OI.U_ID = U.U_ID
JOIN REST_INFO R ON OI.R_ID = R.R_ID
WHERE U.U_NNAME = 'u1'
ORDER BY RI.R_WRIDATE DESC;

-- 메뉴 이름
SELECT
    RI.O_NUM, M.M_NAME
FROM REVIEW_INFO RI
JOIN ORDER_INFO OI ON RI.O_NUM = OI.O_NUM
JOIN ORDER_MENU OM ON OI.O_NUM = OM.O_NUM
JOIN MENU_INFO M ON OM.M_ID = M.M_ID;

-- 리뷰 이미지
SELECT
    O_NUM, R_IMG
FROM REVIEW_IMG;


-- <리뷰 작성시 R_BNAME, U_NNAME 데이터 조회>
SELECT
    R.R_BNAME AS R_BNAME,
    U.U_NNAME AS U_NNAME
FROM
    ORDER_INFO O
    JOIN REST_INFO R ON O.R_ID = R.R_ID
    JOIN USER_INFO U ON O.U_ID = U.U_ID
WHERE
    O.O_NUM = 21;

-- 리뷰 작성
INSERT INTO REVIEW_INFO(O_NUM, R_CONTENT, R_SCORE, R_WRIDATE)
VALUES(21,'정말 맛있어요!',4.5,SYSDATE);

-- 이미지 넣기
INSERT INTO REVIEW_IMG(O_NUM, R_IMG)
VALUES(21,'image.jpg');

-- 리뷰 정보 수정
UPDATE REVIEW_INFO
SET
    R_CONTENT = '수정 내용입니다.',
    R_SCORE = 3.5
WHERE
    O_NUM = 21;

-- 이미지 파일 업데이트
UPDATE REVIEW_IMG
SET
    R_IMG = 'new_image.jpg'
WHERE
    O_NUM = 21;

-- 리뷰 정보 삭제
DELETE FROM REVIEW_INFO
WHERE
    O_NUM = 21;

-- 리뷰 이미지 데이터 삭제
DELETE FROM REVIEW_IMG
WHERE
    O_NUM = 21;